
spring:
   datasource: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://gradeapp-prod.cwcgqfx9ijuw.ap-south-1.rds.amazonaws.com/chandrababu_db
      username: admin
      password: chandrababu
   flyway:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://gradeapp-prod.cwcgqfx9ijuw.ap-south-1.rds.amazonaws.com/gradeapp_student_db
      username: admin
      password: chandrababu 
    